cmake_minimum_required( VERSION 2.8.11 )

set( libiris_INCLUDES
	include/iris/xmpp_stream.h
	include/iris/xmpp_features.h
	include/iris/httppoll.h
	include/iris/xmpp_tasks.h
	include/iris/objectsession.h
	include/iris/xmpp.h
	include/iris/stuntransaction.h
	include/iris/xmpp_url.h
	include/iris/stunbinding.h
	include/iris/netnames.h
	include/iris/xmpp_liveroster.h
	include/iris/im.h
	include/iris/xmpp_agentitem.h
	include/iris/processquit.h
	include/iris/ice176.h
	include/iris/xmpp_chatstate.h
	include/iris/xmpp_jid.h
	include/iris/xmpp_muc.h
	include/iris/xmpp_xdata.h
	include/iris/xmpp_task.h
	include/iris/servsock.h
	include/iris/xmpp_htmlelement.h
	include/iris/httpconnect.h
	include/iris/xmpp_resourcelist.h
	include/iris/xmpp_resource.h
	include/iris/xmpp_stanza.h
	include/iris/xmpp_rosterx.h
	include/iris/bsocket.h
	include/iris/safedelete.h
	include/iris/irisnetexport.h
	include/iris/xmpp_liverosteritem.h
	include/iris/bytestream.h
	include/iris/netavailability.h
	include/iris/udpportreserver.h
	include/iris/addressresolver.h
	include/iris/xmpp_pubsubitem.h
	include/iris/xmpp_roster.h
	include/iris/filetransfer.h
	include/iris/s5b.h
	include/iris/xmpp_status.h
	include/iris/socks.h
	include/iris/xmpp_vcard.h
	include/iris/xmpp_httpauthrequest.h
	include/iris/ndns.h
	include/iris/xmpp_address.h
	include/iris/irisnetplugin.h
	include/iris/xmpp_client.h
	include/iris/xmpp_discoitem.h
	include/iris/irisnetglobal.h
	include/iris/turnclient.h
	include/iris/stunallocate.h
	include/iris/netinterface.h
	include/iris/xmpp_bitsofbinary.h
	include/iris/xmpp_xmlcommon.h
	include/iris/stunmessage.h
	include/iris/srvresolver.h
	include/iris/xmpp_rosteritem.h
	include/iris/xmpp_discoinfotask.h
	include/iris/xmpp_pubsubretraction.h
	include/iris/xmpp_message.h
	include/iris/xmpp_clientstream.h
) 
